version: "3"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/home/node
    ports:
      - 4000:4000
    command: ["yarn", "watch"]
  graphqlviz:
    build:
      context: .
      dockerfile: docker/graphqlviz/Dockerfile
    volumes:
      - .:/home/node
